import { Link } from "react-router-dom";
import { useClientBookingPasses } from "../../../Appointments/bookingPass/useClientBookingPasses.js";
import { formatPassDate, formatPassTime, getBookingStatus } from "../../../Appointments/bookingPass/bookingPassUtils.js";
import ClientPageHeader from "../components/ClientPageHeader.jsx";
import ClientDataState from "../components/ClientDataState.jsx";
import ClientEmptyState from "../components/ClientEmptyState.jsx";

const STATUS_MESSAGES = { pending: "Your request is saved and waiting for the salon to confirm.", confirmed: "Your salon has confirmed this appointment.", completed: "This visit is marked complete. We hope you enjoyed your time.", cancelled: "This appointment has been cancelled." };

export default function NotificationPage() {
  const { appointments, isLoading, error, refetch, isFetching } = useClientBookingPasses();
  return <section className="mx-auto max-w-3xl"><ClientPageHeader eyebrow="Stay in the know" title="Visit updates" description="The latest saved status of your appointments."><button type="button" onClick={() => refetch()} disabled={isFetching} className="min-h-11 rounded-xl border border-ink/15 px-4 text-sm font-medium disabled:opacity-50">{isFetching ? "Refreshing..." : "Refresh updates"}</button></ClientPageHeader><ClientDataState isLoading={isLoading} error={error} onRetry={refetch} isFetching={isFetching}/>{!isLoading && !error && (appointments.length ? <div className="space-y-3">{appointments.map(appointment => { const status = getBookingStatus(appointment.status); return <Link key={appointment.id} to={`/dashboard/my-appointment?appointment=${encodeURIComponent(appointment.id)}`} className="block rounded-2xl border border-ink/10 bg-white/70 p-5 transition hover:bg-white"><span className={`inline-flex rounded-full px-3 py-1.5 text-xs font-medium ${status.tone}`}>{status.label}</span><h2 className="mt-3 text-base font-semibold">{appointment.service_name}</h2><p className="mt-2 text-sm leading-6 text-ink-muted">{STATUS_MESSAGES[appointment.status?.toLowerCase()] || "Open your pass to review this appointment."}</p><div className="mt-4 flex items-center justify-between gap-3 border-t border-ink/10 pt-3 text-xs text-ink-muted"><span>{formatPassDate(appointment.appointment_date)} at {formatPassTime(appointment.appointment_time)}</span><span className="shrink-0 text-ink">View pass &rarr;</span></div></Link>; })}</div> : <ClientEmptyState icon="bell" title="A quiet moment" description="When you book, you can follow your appointment's status here." to="/dashboard/book-appointment?choose_salon=1" actionLabel="Plan a visit"/>)}</section>;
}
