import { VerificationError } from "../_shared/bookingVerification.js";

const corsHeaders = {
  "Cache-Control": "no-store",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

// Only columns already sent by useBookingSubmit. Never spread request data into
// an INSERT, including IDs generated by the DB or verification/ownership flags.
const appointmentFields = [
  "owner_id",
  "client_id",
  "client_name",
  "client_phone",
  "client_email",
  "service_id",
  "service_name",
  "staff_id",
  "staff_name",
  "appointment_date",
  "appointment_time",
  "duration_minutes",
  "price",
  "status",
  "notes",
  "payment_option",
  "payment_method",
  "reward_code",
  "reward_service_ids",
  "reward_profile_id",
];

class BookingError extends Error {
  constructor(status, code, message) {
    super(message);
    this.status = status;
    this.code = code;
  }
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function databaseError(error) {
  // Preserve the codes/details used by the owner's FK retry and missing-table
  // handling; the frontend adapter unwraps this envelope even for non-2xx.
  return json(
    {
      data: null,
      error: {
        message: error.message,
        code: error.code,
        details: error.details,
        hint: error.hint,
      },
    },
    400,
  );
}

async function requireAuthenticatedUser(client, authorization) {
  const token = authorization?.match(/^Bearer\s+(\S+)$/i)?.[1];
  if (!token)
    throw new BookingError(
      401,
      "AUTH_REQUIRED",
      "Please sign in to book an appointment.",
    );
  // Validate remotely with Auth; never authorize from getSession/user_metadata.
  const { data, error } = await client.auth.getUser(token);
  if (error || !data?.user?.id) {
    throw new BookingError(
      401,
      "INVALID_AUTH",
      "Your session is invalid or expired. Please sign in again.",
    );
  }
  return data.user;
}

async function authorizeOwnerBooking(client, authorization, payload) {
  const user = await requireAuthenticatedUser(client, authorization);
  // Existing schema: a salon is the owner's profile, not a separate salons row.
  if (payload.owner_id !== user.id) {
    throw new BookingError(403, "OWNER_REQUIRED", "You do not own this salon.");
  }
  const { data: owner, error } = await client
    .from("profiles")
    .select("id, role")
    .eq("id", user.id)
    .eq("role", "owner")
    .maybeSingle();
  if (error || owner?.id !== user.id || owner?.role !== "owner") {
    throw new BookingError(
      403,
      "OWNER_REQUIRED",
      "An authenticated salon owner is required.",
    );
  }
  return { ...payload, owner_id: user.id, source: "owner" };
}

async function requireCompatibilityClientIdentity(client, authorization, payload) {
  // Temporary compatibility path only. The server-controlled OTP branch below
  // never reaches this function, even when proof validation fails.
  const user = await requireAuthenticatedUser(client, authorization);
  const publicPayload = { ...payload };
  // This field belongs only to owner-assisted reward redemption.
  delete publicPayload.reward_profile_id;
  return {
    ...publicPayload,
    client_id: user.id,
    source: "client",
    status: "Pending",
    payment_option: "Pay at Salon",
  };
}

export function createBookingHandler({
  createUserClient,
  publicMode = "compat",
  createVerifiedAppointment,
}) {
  return async function handleBookingRequest(request) {
    if (request.method === "OPTIONS")
      return new Response(null, { status: 204, headers: corsHeaders });
    if (request.method !== "POST") {
      return json(
        {
          data: null,
          error: { code: "METHOD_NOT_ALLOWED", message: "Use POST." },
        },
        405,
      );
    }
    const path = new URL(request.url).pathname;
    const route = path.match(/\/create-appointment\/(owner|public)\/?$/)?.[1];
    if (!route)
      return json(
        {
          data: null,
          error: { code: "NOT_FOUND", message: "Unknown booking path." },
        },
        404,
      );

    try {
      let body;
      try {
        body = await request.json();
      } catch {
        throw new BookingError(
          400,
          "INVALID_REQUEST",
          "Expected a JSON appointment.",
        );
      }
      const input = body?.appointment;
      if (
        !input ||
        typeof input !== "object" ||
        Array.isArray(input) ||
        typeof input.owner_id !== "string" ||
        !input.owner_id.trim()
      ) {
        throw new BookingError(
          400,
          "INVALID_REQUEST",
          "An appointment with owner_id is required.",
        );
      }
      const payload = Object.fromEntries(
        appointmentFields
          .filter((key) => Object.hasOwn(input, key))
          .map((key) => [key, input[key]]),
      );
      const authorization = request.headers.get("Authorization");

      if (route === "public") {
        // Deployment mode comes only from server configuration, never the body.
        if (!["compat", "otp"].includes(publicMode)) {
          throw new BookingError(
            503,
            "BOOKING_CONFIGURATION",
            "Public booking is unavailable.",
          );
        }
        if (publicMode === "otp" || body.verification !== undefined) {
          if (!body.verification)
            throw new BookingError(
              403,
              "VERIFICATION_REQUIRED",
              "Verify your email before booking.",
            );
          if (!createVerifiedAppointment)
            throw new BookingError(
              503,
              "BOOKING_CONFIGURATION",
              "Public verification is unavailable.",
            );
          try {
            const data = await createVerifiedAppointment(
              payload,
              body.verification,
              authorization,
            );
            return json({ data, error: null });
          } catch (error) {
            // Preserve DB failure codes; never fall back after failed proof.
            if (error instanceof VerificationError) throw error;
            if (
              typeof error?.code === "string" &&
              /^[0-9A-Z]{5}$/.test(error.code)
            )
              return databaseError(error);
            throw error;
          }
        }
      }
      const client = createUserClient(authorization);

      // Route is only requested intent. Owner exemption requires JWT + DB check;
      // public identity authorization stays immediately before persistence.
      const authorizedPayload =
        route === "owner"
          ? await authorizeOwnerBooking(client, authorization, payload)
          : await requireCompatibilityClientIdentity(client, authorization, payload);
      const { data, error } = await client
        .from("appointments")
        .insert(authorizedPayload)
        .select("*");
      if (error) return databaseError(error);
      return json({ data, error: null });
    } catch (error) {
      if (error instanceof BookingError || error instanceof VerificationError) {
        return json(
          { data: null, error: { code: error.code, message: error.message } },
          error.status,
        );
      }
      // Do not expose internal errors or credentials. Do not retry a write whose
      // outcome may be unknown (network interruption after commit).
      return json(
        {
          data: null,
          error: {
            code: "BOOKING_UNAVAILABLE",
            message:
              "Unable to save the appointment. Please check your bookings before trying again.",
          },
        },
        500,
      );
    }
  };
}
