import { useTranslation } from "react-i18next";
import { useState } from "react";
import { Link } from "react-router-dom";
import { formatPassDate } from "../../../Appointments/bookingPass/bookingPassUtils.js";

export default function VisitActivityChart({ months }) {
  const { t } = useTranslation();
  const [selectedKey, setSelectedKey] = useState(null);
  const selected = months.find((month) => month.key === selectedKey);
  const total = months.reduce((sum, month) => sum + month.appointments.length, 0);
  const maximum = Math.max(1, ...months.map((month) => month.appointments.length));
  return <section className="rounded-2xl border border-ink/10 bg-white/70 p-5 sm:p-6" aria-labelledby="visit-activity-title"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-ink-muted">{t("dashboard.yourRoutine")}</p><h2 id="visit-activity-title" className="mt-2 text-xl font-semibold">{t("common.aLittleTimeForYou")}</h2></div><span className="rounded-full bg-cream px-3 py-1.5 text-xs text-ink-muted">{t("dashboard.6Months")}</span></div><p className="mt-2 text-sm text-ink-muted">{total ? t("dashboard.completedVisitTapAMonthToExplore", { count: total }) : t("dashboard.yourCompletedVisitsWillBringThisChartToLife")}</p><div className="mt-5 grid grid-cols-6 gap-2">{months.map(month => <button key={month.key} type="button" aria-pressed={selectedKey === month.key} aria-label={t("dashboard.completedVisits", { value1: month.fullLabel, value2: month.appointments.length })} onClick={() => setSelectedKey(month.key)} className="group min-w-0 rounded-xl px-1 pb-2 pt-3 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ink"><span className="mb-2 block text-xs font-semibold text-ink">{month.appointments.length}</span><span className="relative flex h-28 items-end justify-center rounded-lg bg-cream/80"><span className={`w-full max-w-9 rounded-lg transition-[height,background-color] motion-reduce:transition-none ${selectedKey === month.key ? "bg-ink" : "bg-[#a9b69e] group-hover:bg-[#7c9070]"}`} style={{ height: month.appointments.length ? `${(month.appointments.length / maximum) * 100}%` : "3px" }}/></span><span className={`mt-2 block text-xs ${selectedKey === month.key ? "font-semibold text-ink" : "text-ink-muted"}`}>{month.label}</span></button>)}</div>{selected && <div className="mt-3 rounded-xl bg-cream/60 p-4" aria-live="polite"><h3 className="text-sm font-semibold">{selected.fullLabel}</h3>{selected.appointments.length ? <ul className="mt-2 space-y-2">{selected.appointments.map(appointment => <li key={appointment.id}><Link to={`/dashboard/my-appointment?appointment=${encodeURIComponent(appointment.id)}`} className="flex min-h-11 items-center justify-between gap-3 text-sm"><span>{appointment.service_name}</span><span className="shrink-0 text-xs text-ink-muted">{formatPassDate(appointment.appointment_date)}</span></Link></li>)}</ul> : <p className="mt-2 text-sm text-ink-muted">{t("dashboard.noCompletedVisitsThisMonth")}</p>}</div>}</section>;
}
